/* 
 * Copyright (c) 2015 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc2084.DemoRobot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2084.DemoRobot.Robot;
import org.usfirst.frc2084.DemoRobot.processors.LinearRamper;

/**
 *
 */
public class SpinShooterCommand extends Command {

    private final LinearRamper ramper = new LinearRamper(0.75, LinearRamper.Type.UP);

    public SpinShooterCommand() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        ramper.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.shooterSubsystem.setShooterSpeed(ramper.process(1));
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.shooterSubsystem.setShooterSpeed(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
